# Generated by Django 4.2.4 on 2023-09-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datatable',
            fields=[
                ('roll_no', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('batch', models.CharField(max_length=50)),
                ('mentor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='attendancetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('hour_1', models.BooleanField(default=False)),
                ('hour_2', models.BooleanField(default=False)),
                ('hour_3', models.BooleanField(default=False)),
                ('hour_4', models.BooleanField(default=False)),
                ('hour_5', models.BooleanField(default=False)),
                ('hour_6', models.BooleanField(default=False)),
                ('hour_7', models.BooleanField(default=False)),
                ('hour_8', models.BooleanField(default=False)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='apps.datatable')),
            ],
        ),
    ]
